//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doktor_i_Pacjent_2017_XD_Pro.DBConnectionLogic.SurgeryModel
{
    using System;
    
    public partial class Address
    {
        public string Country { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int StreetNumber { get; set; }
        public Nullable<int> HomeNumber { get; set; }
        public int PostalCode { get; set; }
    }
}
