//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doktor_i_Pacjent_2017_XD_Pro.DBConnectionLogic.SurgeryModel
{
    using System;
    
    public enum Specialization : int
    {
        Surgeon = 0,
        Neurologist = 1,
        Oculist = 2,
        Oncologist = 3,
        Pediatrician = 4,
        Psychiatrist = 5,
        Cardiologist = 6,
        FamilyDoctor = 7
    }
}
